export const AUTH_SECRET_MIN_BYTES = 32;

export const AUTH_SECRET_REQUIREMENTS =
  "AUTH_SECRET must be an unpadded canonical base64url encoding of at least 32 cryptographically random bytes generated by setup; existing noncanonical values require explicit rotation.";

export type AuthSecretValidationReason =
  | "missing"
  | "whitespace"
  | "noncanonical-encoding"
  | "insufficient-bytes"
  | "human-pattern"
  | "valid";

export interface AuthSecretValidationResult {
  valid: boolean;
  reason: AuthSecretValidationReason;
}

const hasRepeatedPattern = (values: ArrayLike<number> | string): boolean => {
  for (let patternLength = 1; patternLength <= Math.min(16, Math.floor(values.length / 2)); patternLength += 1) {
    if (values.length % patternLength !== 0) continue;
    let repeated = true;
    for (let index = patternLength; index < values.length; index += 1) {
      if (values[index] !== values[index % patternLength]) {
        repeated = false;
        break;
      }
    }
    if (repeated) return true;
  }
  return false;
};

const hasOrderedRun = (values: ArrayLike<number> | string, minimumRun = 8): boolean => {
  if (values.length < minimumRun) return false;
  let ascending = 1;
  let descending = 1;
  for (let index = 1; index < values.length; index += 1) {
    const previous = typeof values === "string" ? values.charCodeAt(index - 1) : values[index - 1];
    const current = typeof values === "string" ? values.charCodeAt(index) : values[index];
    ascending = current === previous + 1 ? ascending + 1 : 1;
    descending = current === previous - 1 ? descending + 1 : 1;
    if (ascending >= minimumRun || descending >= minimumRun) return true;
  }
  return false;
};

const decodeCanonicalBase64Url = (value: string): Uint8Array | null => {
  // Reject the legacy hex encoding before base64url decoding; hex's alphabet is
  // a subset of base64url and would otherwise be ambiguously accepted.
  if (/^[A-Fa-f0-9]+$/.test(value) || !/^[A-Za-z0-9_-]+$/.test(value) || value.length % 4 === 1) return null;
  const padded = value
    .replaceAll("-", "+")
    .replaceAll("_", "/")
    .padEnd(Math.ceil(value.length / 4) * 4, "=");
  try {
    const decoded = atob(padded);
    const bytes = Uint8Array.from(decoded, (character) => character.charCodeAt(0));
    const canonical = btoa(String.fromCharCode(...bytes))
      .replaceAll("+", "-")
      .replaceAll("/", "_")
      .replace(/=+$/, "");
    return canonical === value ? bytes : null;
  } catch {
    return null;
  }
};

const isHumanOrPatternedMaterial = (encoded: string, bytes: Uint8Array): boolean => {
  if (hasRepeatedPattern(encoded) || hasOrderedRun(encoded)) return true;
  if (hasRepeatedPattern(bytes) || hasOrderedRun(bytes)) return true;

  // Setup emits random binary material. Fully printable decoded text is a human
  // string wrapped in base64url, not a setup-generated secret.
  return bytes.every((byte) => byte >= 0x20 && byte <= 0x7e);
};

export const validateProductionAuthSecret = (value: string | undefined): AuthSecretValidationResult => {
  if (!value) return { valid: false, reason: "missing" };
  if (value !== value.trim() || /\s/.test(value)) return { valid: false, reason: "whitespace" };

  const bytes = decodeCanonicalBase64Url(value);
  if (!bytes) return { valid: false, reason: "noncanonical-encoding" };
  if (bytes.length < AUTH_SECRET_MIN_BYTES) return { valid: false, reason: "insufficient-bytes" };
  if (isHumanOrPatternedMaterial(value, bytes)) return { valid: false, reason: "human-pattern" };

  return { valid: true, reason: "valid" };
};

export const assertProductionAuthSecret = (value: string | undefined): string => {
  if (!validateProductionAuthSecret(value).valid) {
    throw new Error(AUTH_SECRET_REQUIREMENTS);
  }
  return value as string;
};
